<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:template match="/">
@prefix xsd:	&lt;http://www.w3.org/2001/XMLSchema#&gt;  .
<xsl:for-each select="us-patent-grant/us-bibliographic-data-grant">
&lt;http://us.patents.aksw.org/patent/<xsl:value-of select="publication-reference/document-id/doc-number"/>&gt;    &lt;http://us.patents.aksw.org/schema/hasDocNo&gt;  "<xsl:value-of select="publication-reference/document-id/doc-number"/>"@en    .
&lt;http://us.patents.aksw.org/patent/<xsl:value-of select="publication-reference/document-id/doc-number"/>&gt;    &lt;http://us.patents.aksw.org/schema/hasCountry&gt;  &lt;http://us.patents.aksw.org/patent/<xsl:value-of select="publication-reference/document-id/doc-number"/>/<xsl:value-of select="publication-reference/document-id/country"/>&gt;  .
&lt;http://us.patents.aksw.org/patent/<xsl:value-of select="publication-reference/document-id/doc-number"/>/<xsl:value-of select="publication-reference/document-id/country"/>&gt;    &lt;http://www.w3.org/2000/01/rdf-schema#label&gt;  "<xsl:value-of select="publication-reference/document-id/country"/>"@en  .
&lt;http://us.patents.aksw.org/patent/<xsl:value-of select="publication-reference/document-id/doc-number"/>&gt;    &lt;http://us.patents.aksw.org/schema/kind&gt;  "<xsl:value-of select="publication-reference/document-id/kind"/>"@en  .
&lt;http://us.patents.aksw.org/patent/<xsl:value-of select="publication-reference/document-id/doc-number"/>&gt;    &lt;http://purl/org/dc/terms/date&gt;  "<xsl:value-of select="substring(publication-reference/document-id/date,0,5)"/>-<xsl:value-of select="substring(publication-reference/document-id/date,5,2)"/>-<xsl:value-of select="substring(publication-reference/document-id/date,7,9)"/>"^^xsd:date  .
&lt;http://us.patents.aksw.org/patent/<xsl:value-of select="publication-reference/document-id/doc-number"/>&gt;    &lt;http://us.patents.aksw.org/hasInventionTitle&gt;  "<xsl:value-of select="invention-title"/>"@en  .
<xsl:for-each select="references-cited/citation/patcit">&lt;http://us.patents.aksw.org/patent/<xsl:value-of select="../../publication-reference/document-id/doc-number"/>&gt;    &lt;http://us.patents.aksw.org/schema/citedBy&gt;    &lt;http://us.patents.aksw.org/patent/<xsl:value-of select="document-id/doc-number"/>&gt;  .   
</xsl:for-each>
<xsl:for-each select="references-cited/citation/patcit">
&lt;http://us.patents.aksw.org/patent/<xsl:value-of select="document-id/doc-number"/>&gt;   &lt;http://us.patents.aksw.org/schema/hasCountry&gt;  &lt;http://us.patents.aksw.org/patent/<xsl:value-of select="document-id/doc-number"/>/<xsl:value-of select="document-id/country"/>&gt;  .
&lt;http://us.patents.aksw.org/patent/<xsl:value-of select="document-id/doc-number"/>/<xsl:value-of select="document-id/country"/>&gt;    &lt;http://www.w3.org/2000/01/rdf-schema#label&gt;  "<xsl:value-of select="document-id/country"/>"@en  .
&lt;http://us.patents.aksw.org/patent/<xsl:value-of select="document-id/doc-number"/>&gt;    &lt;http://us.patents.aksw.org/schema/hasNumber&gt;  "<xsl:value-of select="document-id/doc-number"/>"@en  . 
&lt;http://us.patents.aksw.org/patent/<xsl:value-of select="document-id/doc-number"/>&gt;    &lt;http://us.patents.aksw.org/schema/kind&gt;  "<xsl:value-of select="document-id/kind"/>"@en  . 
&lt;http://us.patents.aksw.org/patent/<xsl:value-of select="document-id/doc-number"/>&gt;    &lt;http://us.patents.aksw.org/schema/hasName&gt;  "<xsl:value-of select="document-id/name"/>"@en  .
<xsl:if test="substring(document-id/date,7,9) != '00'">&lt;http://us.patents.aksw.org/patent/<xsl:value-of select="document-id/doc-number"/>&gt;    &lt;http://purl/org/dc/terms/date&gt;  "<xsl:value-of select="substring(document-id/date,0,5)"/>-<xsl:value-of select="substring(document-id/date,5,2)"/>-<xsl:value-of select="substring(document-id/date,7,9)"/>"^^xsd:date  .
</xsl:if><xsl:if test="substring(document-id/date,7,9) = '00'">&lt;http://us.patents.aksw.org/patent/<xsl:value-of select="document-id/doc-number"/>&gt;    &lt;http://purl/org/dc/terms/date&gt;  "<xsl:value-of select="substring(document-id/date,0,5)"/>-<xsl:value-of select="substring(document-id/date,5,2)"/>-01"^^xsd:date  .
</xsl:if>&lt;http://us.patents.aksw.org/patent/<xsl:value-of select="document-id/doc-number"/>&gt;    &lt;http://us.patents.aksw.org/schema/hasCategory&gt;  "<xsl:value-of select="../category"/>"@en  .
</xsl:for-each>
<xsl:for-each select="parties/applicants/applicant">
&lt;http://us.patents.aksw.org/patent/<xsl:value-of select="../../../publication-reference/document-id/doc-number"/>-<xsl:value-of select="addressbook/last-name"/>&gt;     &lt;http://us.patents.aksw.org/schema/hasapplicant&gt; &lt;http://us.patents.aksw.org/applicant/<xsl:value-of select="../../../publication-reference/document-id/doc-number"/>-<xsl:value-of select="addressbook/last-name"/>&gt;  .
&lt;http://us.patents.aksw.org/applicant/<xsl:value-of select="../../../publication-reference/document-id/doc-number"/>-<xsl:value-of select="addressbook/last-name"/>&gt;   &lt;http://xmlns.com/foaf/0.1/lastname&gt;  "<xsl:value-of select="addressbook/last-name"/>"@en  .
&lt;http://us.patents.aksw.org/applicant/<xsl:value-of select="../../../publication-reference/document-id/doc-number"/>-<xsl:value-of select="addressbook/last-name"/>&gt;   &lt;http://xmlns.com/foaf/0.1/firstname&gt;  "<xsl:value-of select="addressbook/first-name"/>"@en  .
&lt;http://us.patents.aksw.org/applicant/<xsl:value-of select="../../../publication-reference/document-id/doc-number"/>-<xsl:value-of select="addressbook/last-name"/>&gt;   &lt;http://us.patents.aksw.org/schema/hasNationality&gt;  "<xsl:value-of select="nationality/country"/>"@en  .
&lt;http://us.patents.aksw.org/applicant/<xsl:value-of select="../../../publication-reference/document-id/doc-number"/>-<xsl:value-of select="addressbook/last-name"/>&gt;   &lt;http://us.patents.aksw.org/schema/hasResidence&gt;  "<xsl:value-of select="residence/country"/>"@en  .
&lt;http://us.patents.aksw.org/applicant/<xsl:value-of select="../../../publication-reference/document-id/doc-number"/>-<xsl:value-of select="addressbook/last-name"/>&gt;   &lt;http://us.patents.aksw.org/schema/city&gt;  "<xsl:value-of select="addressbook/address/city"/>"@en  .
&lt;http://us.patents.aksw.org/applicant/<xsl:value-of select="../../../publication-reference/document-id/doc-number"/>-<xsl:value-of select="addressbook/last-name"/>&gt;   &lt;http://us.patents.aksw.org/schema/state&gt;  "<xsl:value-of select="addressbook/address/state"/>"@en  .
&lt;http://us.patents.aksw.org/applicant/<xsl:value-of select="../../../publication-reference/document-id/doc-number"/>-<xsl:value-of select="addressbook/last-name"/>&gt;   &lt;http://us.patents.aksw.org/schema/hasCountry&gt;  &lt;http://us.patents.aksw.org/applicant/<xsl:value-of select="../../../publication-reference/document-id/doc-number"/>-<xsl:value-of select="addressbook/last-name"/>/<xsl:value-of select="addressbook/address/country"/>&gt;  .
&lt;http://us.patents.aksw.org/applicant/<xsl:value-of select="../../../publication-reference/document-id/doc-number"/>-<xsl:value-of select="addressbook/last-name"/>/<xsl:value-of select="addressbook/address/country"/>&gt;    &lt;http://www.w3.org/2000/01/rdf-schema#label&gt;  "<xsl:value-of select="addressbook/address/country"/>"@en  .
</xsl:for-each> 
</xsl:for-each> 
</xsl:template>
</xsl:stylesheet>
